### PR TITLE
chore(wallet-lib): cherry-pick storage fix

### PR DESCRIPTION
**Pull request by markin-io**
## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by pshenmic — APPROVED** [review]
i recognise it, all good

**Comment by thephez** [comment]
@markin-io Since this was merged to master it should be the v0.22.x milestone, correct? If I'm seeing this incorrectly feel free to move it back to v0.23.0.

**Comment by markin-io** [comment]
@thephez I guess I might not completely understand our milestones systems. Before this moment I considered v0.22 milestone as completed after the v0.22-dev branch merged into the master. Everything else (no matter where it gets merged) is related to the ongoing v0.23 milestone. 

Isn't it how it works? If so, how do we treat PRs that are merged into both master and v0.23?

cc @shumkov

**Comment by thephez** [comment]
@markin-io Good question. The v0.22.0 milestone is closed and now master is v0.22.x milestone. For my purposes, I care mostly about when something is released to "production" (e.g. master) rather than how it fits into the backlog (mainly because there's more urgency for docs when changes go to master). But I can see it from the other perspective too. :slightly_smiling_face: You are probably right, but I'm not sure...

**Pull request merged**
