### PR TITLE
build: `protobufjs` isn't installing from git sometimes

### PR DESCRIPTION
**Pull request by jawid-h**
## Issue being fixed or feature implemented

To avoid issues with installing custom version of `protobufjs`, version from `@dashevo` NPM org is used. Should finalize [https://github.com/dashevo/platform/issues/90](https://github.com/dashevo/platform/issues/90)

## What was done?

- installed `protobuf` from `@dashevo` NPM org

## How Has This Been Tested?

local setup

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by shumkov — APPROVED** [review]
👍

**Comment by thephez** [comment]
Will this also fix #128?

**Comment by shumkov** [comment]
@thephez yep

**Comment by dash-maverick** [comment]
hey, unfortunately it haven't https://github.com/dashevo/platform/issues/128#issuecomment-1079902449 

@jawid-h could you please have another look at this fix and at the error popping up in https://github.com/dashevo/platform/issues/128 ?

**Pull request merged**
