### PR TITLE
build: cache native npm modules during docker build

### PR DESCRIPTION
**Pull request by shumkov**
## Issue being fixed or feature implemented

There are packages that uses node gyp to build native modules. It takes decent amount of time. Previously we had a solution to cache results: https://github.com/frangio/node-gyp-cache

After migration to monorepo, Node 16 and NPM 8, this solution doesn't work anymore.

## What was done?

- Removed node-gyp-cache
- Built slow modules in additional stage and copy the results to eventual node modules dir
- Removed `dashd-zmq-client` from Drive

## How Has This Been Tested?

Running manually

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by strophy** [comment]
Can we run this a few times to test setup times in CI? I think we will still need to remove `npm run clean:data` from the setup script or add back layer caching instead of (or as well as) cache mounts.

**Review by antouhou — APPROVED** [review]

**Comment by shumkov** [comment]
@strophy yeah, I ran it many times and if everything is cached it takes seconds to build. I've updated `clean:data` and going to push it as a separate PR.

**Review by strophy — DISMISSED** [review]
LGTM!

**Review by antouhou — APPROVED** [review]

**Review by strophy — APPROVED** [review]
LGTM! Awesome fix! :1st_place_medal:

**Review by antouhou — APPROVED** [review]

**Pull request merged**
