### PR TITLE
ci(dashmate): remove unnecessary github actions workaround

### PR DESCRIPTION
**Pull request by strophy**
## Issue being fixed or feature implemented

The test suite binary conditional which was supposed to trigger when running in Github Actions cannot trigger since the `node_modules` directory no longer exists anyway.

## What was done?

- Remove Github Actions condition

## How Has This Been Tested?

Locally

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by shumkov** [comment]
@strophy I've cherry-picked this commit right into master to do not change commit hash. The rest of changes I would merge to v0.23-dev.

**Comment by strophy** [comment]
@nmarley this would be another great thing to include in git training - how is it possible to cherry pick a commit which changes a different branch without changing the commit hash? If a change is needed on both branches, what is the correct way to do it?

**Comment by strophy** [comment]
I tried to rebase and got in a massive mess, I don't know how to fix this:
```
strophy@z16:~/Code/dashevo/platform$ git rebase v0.23-dev 
warning: skipped previously applied commit 7db76869
warning: skipped previously applied commit 44cc83dc
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Successfully rebased and updated refs/heads/fix-master-test-suite.
strophy@z16:~/Code/dashevo/platform$ git status
On branch fix-master-test-suite
Your branch and 'origin/fix-master-test-suite' have diverged,
and have 111 and 6 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
strophy@z16:~/Code/dashevo/platform$ git pull
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

**Comment by nmarley** [comment]
@strophy I would need more clarification from Ivan as to what he means about not changing commit hash. AFAIK the commit hash takes previous (base) commits as part of the hash payload, as well as metadata like timestamp and name/email, so it would be really hard to not change the commit hash. But Ivan might be referring to something on the `master` or `v0.23-dev` branches or something else I'm not understanding w/o context.

If a change is needed on both branches, then it should be applied to both branches, and assuming they're divergent. That is more a question of git workflow / strategy. Here is an example of one way to do it, please read the "Hotfix branches" part: https://nvie.com/posts/a-successful-git-branching-model/#hotfix-branches

I can try and help fix your mess if we can get on a call together. Generally when git says `use "git pull" to merge the remote branch into yours`, I try and avoid that as it's usually not what I want.

Would love to prep a git training brown bag, I can start working on it in a couple weeks.

**Comment by shumkov** [comment]
We already have it from master

**Pull request closed without merging**
